# Generated by Django 5.2.5 on 2025-08-19 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='modified_date',
            field=models.DateTimeField(verbose_name='date modified'),
        ),
    ]
